label_folder: "/path/to/OpenSAR/data/use_cases/rfi/aresys_full_split/rfi_aresys_dataset/train/labels/xml_labelling/"
product_folder: "/path/to/opensar/UAH_rfi_labeling/RFI_Codes_Python/inputs/slc/"
output_file: "/path/to/opensar/UAH_rfi_labeling/RFI_Codes_Python/inputs/output.npy"
log_file: "/path/to/opensar/code/backend/data/tmp/traceability.log"