processing:
  scenes_to_process: [1,3]
paths:
  input_root: "/path/to/opensar/artifacts/dataset_generation/flood/input"
  output_root: "/path/to/opensar/artifacts/dataset_generation/flood_test"
  floods_mapping_csv: "/path/to/opensar/code/backend/dataset_generation_scripts/FD_dataset_generation/scene_mapping.csv"
options:
  USE_AOI_EXACT_POLYGON: false
  SIZEPATCH: 512
