"""
---------------------------------------------------------------------
Project: OpenSAR Insight
---------------------------------------------------------------------
create_data_yaml.py

Tool: Create YOLO data.yaml configuration file

Author: Abdulhameed Yunusa (ABHY)
E-mail: ayunusa@indracompany.com
Creation Date: 2026-02-26

© Copyright INDRA DEIMOS, 2026. All rights reserved.
---------------------------------------------------------------------
"""
# type: ignore
from pathlib import Path


def create_data_yaml(yolo_dataset_path: Path, class_names: list = None):
    """
    Create data.yaml file for YOLO training.
    
    Args:
        yolo_dataset_path: Root path of the YOLO dataset
        class_names: List of class names (default: ['vessel'])
    """
    if class_names is None:
        class_names = ['vessel']
    
    data_yaml_content = f"""# YOLO Dataset Configuration
# Auto-generated by generate_yolo_labels.py

path: {yolo_dataset_path}
train: images/train
val: images/val
test: images/test

# Classes
nc: {len(class_names)}
names: {class_names}
"""
    
    data_yaml_path = Path('data.yaml')
    data_yaml_path.write_text(data_yaml_content)
    print(f"Created data.yaml at: {data_yaml_path}")